### ISSUE TITLE
traefik to manage subdomains; nginx on root

### ISSUE THREAD

**Issue by gavin771** [cedricziel/traefik-proxample#1]
Not really an issue, but Im wondering how would the configuration look if I want to use traefik to proxy requests for my subdomains and use nginx on my root.

so i want to serve up some static files to: domain.com
but i want traefik to handle traffic to: app.domain.com, app2.domain.com

here is what i have in my composer file....

version: '3'

networks:
  proxy:
    external: true
  internal:
    external: false
services:
  traefik:
    image: traefik:alpine
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    restart: always
    labels:
      - logLevel="DEBUG"
      - "traefik.backend=monitor"
      - "traefik.frontend.rule=Host:monitor.domain.com"
      - "traefik.port=8080"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.enable=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.toml:/traefik.toml"
      - "./acme.json:/acme.json"
    expose:
      - "8080"
    networks:
      - internal
      - proxy
  custom-badge:
    image: app
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    labels:
      - traefik.enabled=true
      - traefik.backend=custom-badge
      - traefik.frontend.rule=Host:app.domain.com
      - traefik.docker.network=proxy
      - traefik.port=3000
    networks:
      - internal
      - proxy
  server:
    image: nginx:alpine
    ports:
       - "80:80"
    labels:
      - traefik.enabled=true
      - traefik.backend=
      - traefik.frontend.rule=domain.com
      - traefik.docker.network=proxy
      - traefik.port=80
    volumes:
      - "./apps/root:/etc/nginx/html:ro"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    environment:
      - NGINX_HOST=domain.com
      - NGINX_PORT=80
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - traefik

Im getting port conflict errors, what am i doing wrong?

**Comment by gavin771** [comment]
Got it working, needed to remove the port section of nginx. Allowing traefik to manage the traffic to go there too

**Comment by cedricziel** [comment]
Great - thank you for the feedback!
